### ISSUE TITLE
[BUG] '去除空格' 导致复制引用块或嵌入块失效

### ISSUE THREAD

**Issue by DostGit** [Achuan-2/siyuan-plugin-text-process#1]
![SiYuan_nOYFYPGcDr](https://github.com/user-attachments/assets/bf374b4c-d4b7-40df-ad3b-2c88ddcf9c58)
![SiYuan_1WCbM3ocs6](https://github.com/user-attachments/assets/c4229d71-fbb0-4b5c-86b1-1f2c3b3f8224)

**Comment by Achuan-2** [comment]
这不算bug哦，这就是去除空格的效果

**Comment by Achuan-2** [comment]
尝试排除了下

**Comment by DostGit** [comment]
> 这不算bug哦，这就是去除空格的效果，只不过思源的块引和嵌入块需要空格 而且思源复制块引等操作也是识别为纯文本粘贴，没处理为siyuanHTML专属格式，也没法直接根据格式识别 去除空格一般从外部复制内容的时候再开启，不建议一直开启 latex公式转换和富文本列表粘贴默认一直开启应该是没问题的

好的，感谢作者大大，很有用
