### ISSUE TITLE
【enhancement】希望能在“对块操作”的列表中加入“去除html格式”，当然最好是能做一个简单的转化

### ISSUE THREAD

**Issue by Tim-Devil** [Achuan-2/siyuan-plugin-text-process#5]
有时候一些博客会用html对文章进行美化，如果从github上下载下来markdown文档就会看到一大堆<span>之类的标签，非常难处理。希望能够增加功能，在块中去除这些标签！
当然更好的则是做一个简单的替换，比如只要带颜色就变成高亮，加粗就加粗……像这样的简单的一个转换。

**Comment by Achuan-2** [comment]
用思源的剪藏功能应该不会保留这些标签吧
另外你需要给我示例网址，我没有遇见过这种Markdown

**Comment by Tim-Devil** [comment]
https://axyzdong.github.io/Signals-and-Systems/#/ch4/ch4.2
其实主要是遇到了这个网址，直接剪藏会发现问题很大（虽然我也不知道为什么会这样）
我是直接用插件导出的，大佬如果方便的话也可以试一😭Thanks in advance!

**Comment by Achuan-2** [comment]
我这边除了高亮样式，没有其他问题
高亮样式是因为作者本来就没有激活，思源就转义了
![PixPin_2024-12-16_14-46-26](https://github.com/user-attachments/assets/fcf738ac-59ba-46a9-aa09-8536940e3f62)
解决方法就是复制为纯文本，然后ctrl+V粘贴就能保留样式了，不需要插件的
