### ISSUE TITLE
思源从0.02版本之后，集市一直显示更新状态……

### ISSUE THREAD

**Issue by daoyepro** [Achuan-2/siyuan-plugin-text-process#8]
思源从0.02版本之后，集市一直显示更新状态……

更新完也不动，还是0.02，删也删不掉，一直在已下载里，文件夹我都手动删了，还是显示更新。怎么破？！

![1734615980481](https://github.com/user-attachments/assets/8991a6ca-3165-4d48-9405-01fc04097e29)

**Comment by Achuan-2** [comment]
可能你之前是下载的压缩包安装的插件，
思源非集市安装插件有各种问题的，会出现明明删除文件夹，插件还安装在思源里的情况

**Comment by Achuan-2** [comment]
可以关闭思源再启动思源，看看插件是否卸载成功
否则就得更新思源最新版
